FROM node:17.4.0
MAINTAINER Agus Kwee (aguskwee@smu.edu.sg)

# update and install necessary packages
RUN apt-get update && \
	apt-get upgrade -y

# get parameter arguments
ARG MONGO_URL
ARG RABBITMQ_URL

RUN mkdir payments
WORKDIR payments

# copy files
COPY payment.js paymentModel.js package.json ./

# install dependencies
RUN npm install

# environment variables
ENV MONGO_URL=$MONGO_URL
ENV RABBITMQ_URL=$RABBITMQ_URL

ENTRYPOINT ["npm", "start"]