FROM node:17.4.0
MAINTAINER Agus Kwee (aguskwee@smu.edu.sg)

# update and install necessary packages
RUN apt-get update && \
	apt-get upgrade -y

# get parameter arguments
ARG MONGO_URL

RUN mkdir customers
WORKDIR customers

# copy files
COPY customer.js customerModel.js package.json ./

# install dependencies
RUN npm install

# environment variables
ENV MONGO_URL=$MONGO_URL

ENTRYPOINT ["npm", "start"]